# Generated by Django 2.2.16 on 2021-02-07 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('username', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(blank=True, max_length=200)),
                ('user_type', models.CharField(blank=True, max_length=50)),
                ('is_approved', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateField(verbose_name=datetime.datetime(2021, 2, 7, 15, 59, 18, 924468))),
                ('modified_at', models.DateField(verbose_name=datetime.datetime(2021, 2, 7, 15, 59, 18, 924504))),
            ],
        ),
    ]
