# Generated by Django 2.2.16 on 2021-02-07 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateField(verbose_name=datetime.datetime(2021, 2, 7, 16, 1, 13, 1923)),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified_at',
            field=models.DateField(verbose_name=datetime.datetime(2021, 2, 7, 16, 1, 13, 1956)),
        ),
    ]
